# Generated by Django 6.1.1 on 2026-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
