# Generated by Django 6.1.1 on 2026-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipement_projetsportif_demande_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='heure',
            new_name='heure_debut',
        ),
        migrations.AddField(
            model_name='reservation',
            name='heure_fin',
            field=models.TimeField(default='00:00'),
        ),
    ]
